db_hostname = "db.host"
db_dbname = "db_name"
db_username = "db_user"
db_password = "db_pass"

tbl_files = "ZZfiles"
tbl_assoc = "ZZassoc"
tbl_tags = "ZZtags"
tbl_types = "ZZtypes"
tbl_inherit = "ZZinheritances"
tbl_aliases = "ZZalias"
tbl_recent = "ZZrecent"
tbl_bans = "ZZbans"
tbl_activity = "ZZactivity"
tbl_priv = "ZZprivileged"
